variables:
  OPENSHIFT_SERVER: "https://console.pre.ocp.binter.cl:8443"
  OPENSHIFT_DOMAIN: "apps.pre.ocp.binter.cl"
  APP: "qcdvaluationengine"
  OPENSHIFT_PROYECT_QA: "frontdesk-qa"
  NON_PROD_REGISTRY: "docker-registry-default.apps.pre.ocp.binter.cl"
  TAG_DOCKER: "${CI_PIPELINE_ID}_${CI_COMMIT_SHORT_SHA}"

stages:
  - build
      
build:
  stage: build
  image: "openshift3/jenkins-slave-base-rhel7"
  before_script:
    - "oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify"
    - "oc project $OPENSHIFT_PROYECT_QA"
  script:
    - "oc whoami"
    - "oc get bc centos_builder 2> /dev/null || oc new-build ./centos_builder --name=centos-builder --strategy=docker"
    - "oc start-build $APP --from-dir=./centos_builder --follow"
  only:
    - docker
  except:
    - schedules
  tags:
    - non-prod
